language: ruby
rvm:
  - 2.3.0
cache: bundler
services:
  - postgresql

before_install:
  - gem update --system
  - gem --version
  - bundle install
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake

before_script:
  - psql -c 'create database workdey_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
  - java -jar selenium-server-standalone-2.31.0.jar
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake spec:features
bundler_args: --binstubs=./bundler_stubs
